### ISSUE TITLE
Remove duplication in Quincy cost models (simulated vs. real cluster)

### ISSUE THREAD

**Issue by ICGog** [ms705/firmament#21]
The simulated Quincy should wrap around the real Quincy model and feed it with simulated data locality information.

**Comment by ms705** [comment]
[CL 266326](https://review.gerrithub.io/#/c/266326/) addresses this, but we're planning on moving to a unified Quincy cost model that abstracts the distributed file system through a universal interface that works for the simulated GFS (in simulation) and real-world HDFS (when running on real clusters).

I'll leave the issue open until this is implemented, but change the title to a more accurate one.

**Comment by ms705** [comment]
I believe this is fixed as of [CL 266533](https://review.gerrithub.io/#/c/266533/) (0b8305f3e25c02d0a87349a86e4678bc06f20344). Good to close?

**Comment by ICGog** [comment]
Yes, we've merged them.
