### ISSUE TITLE
Arcs between ECs don't get updated.

### ISSUE THREAD

**Issue by ICGog** [ms705/firmament#38]
Currently, the capacity and cost of the arcs connecting equivalence classes do not get updated. This is not a problem for our current cost models because they don't have arcs between ECs. However, we still want to update the arcs because we may add cost models that require this feature.

**Comment by ms705** [comment]
I believe [262172](https://review.gerrithub.io/#/c/262172/) (merged as fa41f2e1606575cc536796d82b0f49b0424ef3f7) fixes this bug? Can it be closed?

**Comment by ICGog** [comment]
Yes, that's true.
